TheWorld/src/TheWorld/Models/Trip.cs
namespace TheWorld.Models
{
    using System;
    using System.Collections.Generic;

    public class Trip
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime Created { get; set; }
        public string UserName { get; set; }

        public ICollection<Stop> Stops { get; set; }
    }
}

TheWorld/src/TheWorld/ViewModels/ContactViewModel.cs
namespace TheWorld.ViewModels
{
    using System.ComponentModel.DataAnnotations;

    public class ContactViewModel
    {
        [Required]
        [StringLength(255, MinimumLength = 5)]
        public string Name { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [StringLength(1024, MinimumLength = 5)]
        public string Message { get; set; }
    }  
}

TheWorld/src/TheWorld/ViewModels/TripViewModel.cs
namespace TheWorld.ViewModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Models;

    public class TripViewModel
    {
        public int Id { get; set; }

        [Required]
        [StringLength(255, MinimumLength = 5)]
        public string Name { get; set; }

        public DateTime Created { get; set; } = DateTime.UtcNow;

        public IEnumerable<Stop> Stops { get; set; } 
    }
}

TheWorld/src/TheWorld/Controllers/Api/TripController.cs
namespace TheWorld.Controllers.Api
{
    using System;
    using System.Collections.Generic;
    using System.Net;
    using AutoMapper;
    using Microsoft.AspNet.Authorization;
    using Microsoft.AspNet.Mvc;
    using Microsoft.Extensions.Logging;
    using Models;
    using ViewModels;

    [Authorize]
    [Route("api/trips")]
    public class TripController : Controller
    {
        private readonly IWorldRepository repository;
        private readonly ILogger<TripController> logger;

        public TripController(IWorldRepository repository, ILogger<TripController> logger)
        {
            this.repository = repository;
            this.logger = logger;
        }

        [HttpGet]
        public JsonResult Get()
        {
            try
            {
                var trips = this.repository.GetUserTripsWithStops(User.Identity.Name);
                var results = Mapper.Map<IEnumerable<TripViewModel>>(trips);
                return Json(results);
            }
            catch (Exception ex)
            {
                this.logger.LogError("Error in Get", ex);
                return Json(ex.Message);
            }
        }

        [HttpPost]
        public JsonResult Post([FromBody]TripViewModel vm)
        {
            try
            {
                if (this.ModelState.IsValid)
                {
                    var trip = Mapper.Map<Trip>(vm);
                    trip.UserName = this.User.Identity.Name;

                    // Save to db
                    this.logger.LogInformation("Attempting to save to db");
                    this.repository.AddTrip(trip);

                    if (this.repository.SaveAll())
                    {
                        this.Response.StatusCode = (int)HttpStatusCode.Created;
                        return Json(Mapper.Map<TripViewModel>(trip));
                    }
                }
            }
            catch (Exception ex)
            {
                this.logger.LogError("Exception in Post", ex);
                this.Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(new { Message = "Failed", ModelState = ex.Message });
            }

            this.Response.StatusCode = (int)HttpStatusCode.BadRequest;
            return Json(new {Message = "Failed", ModelState = this.ModelState});
        }
    }
}

TheWorld/src/TheWorld/Controllers/Web/AppController.cs
namespace TheWorld.Controllers.Web
{
    using System;
    using Microsoft.AspNet.Mvc;
    using Microsoft.AspNet.Authorization;
    using Models;
    using Services.MailService;
    using ViewModels;

    public class AppController : Controller
    {
        private IMailService mailService;
        private IWorldRepository repository;

        public AppController(IMailService mailService, IWorldRepository repository)
        {
            this.mailService = mailService;
            this.repository = repository;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        public IActionResult Trips()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Contact(ContactViewModel viewModel)
        {
            if (this.ModelState.IsValid)
            {
                var email = Startup.Configuration["AppSettings:SiteEmailAddress"];

                if (string.IsNullOrWhiteSpace(email))
                {
                    throw new Exception("Email is null");
                }

                if (this.mailService.SendMail(email, email, $"Contact from {viewModel.Email}", viewModel.Message))
                {
                    this.ModelState.Clear();

                    this.ViewBag.Message = "Meesage sent, thanks!";
                }
            }
            return View();
        }
    }
}

TheWorld/src/TheWorld/Views/App/About.cshtml
@{
    ViewBag.Title = "About Page";
}

<h2>About Alex</h2>

TheWorld/src/TheWorld/Views/App/Contact.cshtml
@model TheWorld.ViewModels.ContactViewModel
@{
    ViewBag.Title = "Contact Page";
}

@section Scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h2>Contact Alex</h2>
        <form method="post">
            @if (ViewBag.Message != null)
            {
                <div>@ViewBag.Message</div>
            }
            <div asp-validation-summary="ValidationSummary.ModelOnly"></div>

            <div class="form-group">
                <label asp-for="Name">Name</label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-muted"></span>
            </div>

            <div class="form-group">
                <label asp-for="Email">Email</label>
                <input type="email" asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-muted"></span>
            </div>

            <div class="form-group">
                <label asp-for="Message">Message</label>
                <textarea cols="40" rows="4" asp-for="Message" class="form-control"></textarea>
                <span asp-validation-for="Message" class="text-muted"></span>
            </div>

            <div class="form-group">
                <a asp-controller="App" asp-action="Index" class="btn btn-default">Cancel</a>
                <input type="submit" value="Send Message" class="btn btn-success"/>
            </div>
        </form>
    </div>
</div>

TheWorld/src/TheWorld/Views/App/Index.cshtml
@model IEnumerable<TheWorld.Models.Trip>
@{
    ViewBag.Title = "Hello World";
}

<div class="row">
    <div class="col-md-12">
        <h1>Welcome to the World!</h1>
        <p>Blah blah blah</p>
        <a asp-controller="App" asp-action="trips" class="btn btn-lg btn-success">View my trips</a>
    </div>
</div>

TheWorld/src/TheWorld/Views/App/Trips.cshtml
@{
    ViewBag.Title = "Hello World";
}

@section Scripts {
    <script src="https://maps.googleapis.com/maps/api/js?sensor=true"></script>

    <enviroment names="Development">
        <script src="~/lib/underscore/underscore.js"></script>
        <script src="~/lib/angular/angular.js"></script>
        <script src="~/lib/angular-route/angular-route.js"></script>
        <script src="~/lib/gmaps/gmaps.js"></script>
        <script src="~/lib/travelmap/travelmap.js"></script>
        <script src="~/js/app-trips.js"></script>
        <script src="~/js/tripsController.js"></script>
        <script src="~/js/simpleControls.js"></script>
        <script src="~/js/tripEditorController.js"></script>
    </enviroment>

    <enviroment names="Production,Staging">
        <script src="~/lib/underscore/underscore-min.js"></script>
        <script src="~/lib/angular/angular.min.js"></script>
        <script src="~/lib/angular-route/angular-route.min.js"></script>
        <script src="~/lib/gmaps/gmaps.min.js"></script>
        <script src="~/lib/travelmap/travelmap.min.js"></script>
        <script src="~/lib/_app/app-trips.js"></script>
        <script src="~/lib/_app/tripsController.js"></script>
        <script src="~/lib/_app/simpleControls.js"></script>
        <script src="~/lib/_app/tripEditorController.js"></script>
    </enviroment>
}

<div class="row" ng-app="app-trips">
    <div ng-view></div>
</div>